import 'package:flutter/material.dart';

class FruitsInfo with ChangeNotifier {
  List<Map<String, dynamic>> _fruitsNew = [
    {
      "id": "1",
      "cmnName": "Apple",
      "scfName": "Malus domestica",
      "color1": Colors.red[100],
      "slDescription":
          "An apple is a sweet, edible fruit produced by an apple tree . It is one of the most popular fruits on the planet .",
      "description":
          """An apple is an edible fruit produced by an apple tree (Malus domestica). Apples have been grown for thousands of years in Asia and Europe and were brought to North America by European colonists. Apples have religious and mythological significance in many cultures, including Norse, Greek, and European Christian tradition. The word apple, formerly spelled \u00e6ppel in Old English, is derived from the Proto-Germanic root *ap(a)laz, which could also mean fruit in general.\n\nWorldwide production of apples in 2018 was 86 million tonnes, with China accounting for nearly half of the total.""",
      "imgUrl": "f_01.webp",
      "calories": 52,
      "carb": 13.81,
      "sugar": 10.39,
      "fiber": 2.4,
      "fat": 0.17,
      "protein": 0.26,
      "water": 85.56,
      "vitA": 0.003,
      "vitB1": 0.017,
      "vitB2": 0.026,
      "vitB3": 0.091,
      "vitB5": 0.061,
      "vitB6": 0.041,
      "vitB7": 0,
      "vitB9": 0.003,
      "vitB12": 0,
      "vitC": 4.6,
      "vitD": 0,
      "vitE": 0.18,
      "vitK": 0.0022,
      "choline": 0,
      "potassium": 107,
      "chlorine": 0,
      "sodium": 1,
      "calcium": 6,
      "phosphorus": 11,
      "magnesium": 5,
      "iron": 0.12,
      "zinc": 0.04,
      "manganese": 0.035,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_01.webp"
    },
    {
      "id": "2",
      "cmnName": "Pear",
      "scfName": "Pyrus communis",
      "color1": Colors.amber[100],
      "slDescription":
          "A pear is a mild, sweet fruit with a fibrous center. Pears are rich in essential antioxidants, plant compounds, and dietary fiber.",
      "description":
          """Pears are fruits produced and consumed around the world, growing on a tree and harvested in the Northern Hemisphere in late summer into October. About 3000 known varieties of pears are grown worldwide, which vary in both shape and taste. The fruit is consumed fresh, canned, as juice, or dried.\n\nThe word pear is probably from Germanic pera as a loanword of Vulgar Latin pira, the plural of pirum, akin to Greek apios (from Mycenaean \u00e1pisos), of Semitic origin (pir\u00e2), meaning \"fruit\". Pear cultivation in cool, temperate climates extends to the remotest antiquity, and evidence exists of its use as a food since prehistoric times.\n\nIn 2018, world production of pears was 23.7 million tonnes, led by China with 68% of the total.\n""",
      "imgUrl": "f_02.webp",
      "calories": 57,
      "carb": 15.23,
      "sugar": 9.75,
      "fiber": 3.1,
      "fat": 0.14,
      "protein": 0.36,
      "water": 84,
      "vitA": 0,
      "vitB1": 0.012,
      "vitB2": 0.026,
      "vitB3": 0.161,
      "vitB5": 0.049,
      "vitB6": 0.029,
      "vitB7": 0,
      "vitB9": 0.007,
      "vitB12": 0,
      "vitC": 4.3,
      "vitD": 0,
      "vitE": 0.12,
      "vitK": 0.0044,
      "choline": 5.1,
      "potassium": 116,
      "chlorine": 0,
      "sodium": 1,
      "calcium": 9,
      "phosphorus": 12,
      "magnesium": 7,
      "iron": 0.18,
      "zinc": 0.1,
      "manganese": 0.048,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_02.webp"
    },
    {
      "id": "3",
      "cmnName": "Banana",
      "scfName": "Musa acuminata",
      "color1": Colors.yellow[100],
      "slDescription":
          "Bananas are one of the most popular fruits worldwide. They contain essential nutrients that can have a protective impact .",
      "description":
          """A banana is an elongated, edible fruit. In some countries, bananas used for cooking may be called \"plantains\", distinguishing them from dessert bananas. \n\nAn article on Banana tree cultivation is brought down in Ibn al-'Awwam's 12th-century agricultural work, Book on Agriculture. Bananas were cultivated by Papuans before the arrival of Austronesian-speakers. There is evidence that bananas were also known to the Indus Valley Civilisation from phytoliths recovered from the Kot Diji archaeological site in Pakistan.\n\nIn 2017, world production of bananas and plantains combined was 153 million tonnes, led by India and China with a combined total of 27% of global production.\n""",
      "imgUrl": "f_03.webp",
      "calories": 89,
      "carb": 22.84,
      "sugar": 12.23,
      "fiber": 2.6,
      "fat": 0.33,
      "protein": 1.09,
      "water": 74.91,
      "vitA": 0,
      "vitB1": 0.031,
      "vitB2": 0.073,
      "vitB3": 0.665,
      "vitB5": 0.334,
      "vitB6": 0.4,
      "vitB7": 0,
      "vitB9": 0.02,
      "vitB12": 0,
      "vitC": 8.7,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0,
      "choline": 9.8,
      "potassium": 358,
      "chlorine": 0,
      "sodium": 1,
      "calcium": 0,
      "phosphorus": 22,
      "magnesium": 27,
      "iron": 0.26,
      "zinc": 0.15,
      "manganese": 0.27,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_03.webp"
    },
    {
      "id": "4",
      "cmnName": "Orange",
      "scfName": "Citrus X sinensis",
      "color1": Colors.orange[100],
      "slDescription":
          "An orange is a type of citrus fruit that people often eat. Oranges are a very good source of Vitamin C.",
      "description":
          """The orange originated in a region encompassing Southern China, Northeast India, and Myanmar, and the earliest mention of the sweet orange was in Chinese literature in 314 BC. As of 1987, orange trees were found to be the most cultivated fruit tree in the world. The fruit of the orange tree can be eaten fresh, or processed for its juice or fragrant peel.\n\nThe word orange derives from the Sanskrit word for \"orange tree\" (n\u0101ra\u1e45ga), which in turn derives from a Dravidian root word narandam/naranja which refers to Bitter orange in Tamil and Malayalam.\n\nIn 2019, 79 million tonnes of oranges were grown worldwide, with Brazil producing 22% of the total, followed by China and India.""",
      "imgUrl": "f_04.webp",
      "calories": 47,
      "carb": 11.75,
      "sugar": 9.35,
      "fiber": 2.4,
      "fat": 0.12,
      "protein": 0.94,
      "water": 88.75,
      "vitA": 0.011,
      "vitB1": 0.087,
      "vitB2": 0.004,
      "vitB3": 0.282,
      "vitB5": 0.25,
      "vitB6": 0.06,
      "vitB7": 0,
      "vitB9": 0.03,
      "vitB12": 0,
      "vitC": 53.2,
      "vitD": 0,
      "vitE": 0.18,
      "vitK": 0,
      "choline": 8.4,
      "potassium": 181,
      "chlorine": 0,
      "sodium": 0,
      "calcium": 40,
      "phosphorus": 14,
      "magnesium": 10,
      "iron": 0.1,
      "zinc": 0.07,
      "manganese": 0.025,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_04.webp"
    },
    {
      "id": "5",
      "cmnName": "Lemon",
      "scfName": "Citrus limon",
      "color1": Colors.yellow[100],
      "slDescription":
          "A lemon is a yellow citrus fruit. It is related to the orange. Lemon juice is about 5% citric acid, and has a pH of 2 to 3. Lemon plants vary in size yet stay generally small. The tallest height they can get is about 6 meters tall.",
      "description":
          """The lemon is a species of small evergreen tree native to South Asia, primarily Northeast India (Assam). The tree's ellipsoidal yellow fruit is used for culinary and non-culinary purposes throughout the world, primarily for its juice, which has both culinary and cleaning uses.\n\nThe origin of the lemon is unknown, though lemons are thought to have first grown in Assam (a region in northeast India), northern Burma or China.\n\nIn 2018, world production of lemons (combined with limes for reporting) was 19.4 million tonnes. The top producers \u2013 India, Mexico, China, Argentina, Brazil, and Turkey \u2013 collectively accounted for 65% of global production.""",
      "imgUrl": "f_05.webp",
      "calories": 29,
      "carb": 9.32,
      "sugar": 2.5,
      "fiber": 2.8,
      "fat": 0.3,
      "protein": 1.1,
      "water": 88.68,
      "vitA": 0,
      "vitB1": 0.04,
      "vitB2": 0.02,
      "vitB3": 0.1,
      "vitB5": 0.19,
      "vitB6": 0.08,
      "vitB7": 0,
      "vitB9": 0.011,
      "vitB12": 0,
      "vitC": 5.1,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0,
      "choline": 5.1,
      "potassium": 138,
      "chlorine": 0,
      "sodium": 0,
      "calcium": 26,
      "phosphorus": 16,
      "magnesium": 8,
      "iron": 0.6,
      "zinc": 0.06,
      "manganese": 0.03,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_05.webp"
    },
    {
      "id": "6",
      "cmnName": "Peach",
      "scfName": "Prunus persica",
      "color1": Colors.pink[100],
      "slDescription":
          "Peaches are a fuzzy fruit native to northwest China. They are a member of the stone fruit family, which means that their flesh surrounds one large middle seed",
      "description":
          """The peach is a deciduous tree native to the region of Northwest China between the Tarim Basin and the north slopes of the Kunlun Mountains, where it was first domesticated and cultivated. It bears edible juicy fruits with various characteristics, most called peaches and others (the glossy-skinned varieties), nectarines.\n\nGenetic studies suggest peaches originated in China. Recent evidence indicates that domestication occurred as early as 6000 BC in Zhejiang Province of China. Peach cultivation reached Greece by 300 BC. Alexander the Great is sometimes said to have introduced them into Greece after conquering Persia, but no historical evidence for this claim has been found.\n\nIn 2018, China produced 62% of the world total of peaches and nectarines.""",
      "imgUrl": "f_06.webp",
      "calories": 39,
      "carb": 9.54,
      "sugar": 8.39,
      "fiber": 1.5,
      "fat": 0.25,
      "protein": 0.91,
      "water": 89,
      "vitA": 0.016,
      "vitB1": 0.024,
      "vitB2": 0.031,
      "vitB3": 0.806,
      "vitB5": 0.153,
      "vitB6": 0.025,
      "vitB7": 0,
      "vitB9": 0.004,
      "vitB12": 0,
      "vitC": 6.6,
      "vitD": 0,
      "vitE": 0.73,
      "vitK": 0.0026,
      "choline": 6.1,
      "potassium": 190,
      "chlorine": 0,
      "sodium": 0,
      "calcium": 6,
      "phosphorus": 20,
      "magnesium": 9,
      "iron": 0.25,
      "zinc": 0.17,
      "manganese": 0.061,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_06.webp"
    },
    {
      "id": "7",
      "cmnName": "Grapes",
      "scfName": "Vitis vinifera",
      "color1": Colors.purple[100],
      "slDescription":
          "Grapes are a type of fruit that grow in clusters of 15 to 300, and can be crimson, black, dark blue, yellow, green, orange, and pink.",
      "description":
          """Grapes can be eaten fresh, used for making wine, jam, grape juice, jelly, grape seed extract, vinegar, and grape seed oil, or dried as raisins, currants and sultanas. \n\nThe Middle East is generally described as the homeland of grape and the cultivation of this plant began there 6,000\u20138,000 years ago. Yeast, one of the earliest domesticated microorganisms, occurs naturally on the skins of grapes, leading to the discovery of alcoholic drinks such as wine. The earliest archeological evidence for a dominant position of wine-making in human culture dates from 8,000 years ago in Georgia.\n\nChina was the largest producer of grapes, accounting for 16.9% of global production. Italy came second at 10.8%, followed by the United States at 8.7%.""",
      "imgUrl": "f_07.webp",
      "calories": 69,
      "carb": 18.1,
      "sugar": 15.48,
      "fiber": 0.9,
      "fat": 0.16,
      "protein": 0.72,
      "water": 81,
      "vitA": 0,
      "vitB1": 0.069,
      "vitB2": 0.07,
      "vitB3": 0.188,
      "vitB5": 0.05,
      "vitB6": 0.086,
      "vitB7": 0,
      "vitB9": 0.002,
      "vitB12": 0,
      "vitC": 3.2,
      "vitD": 0,
      "vitE": 0.19,
      "vitK": 0.0146,
      "choline": 5.6,
      "potassium": 191,
      "chlorine": 0,
      "sodium": 2,
      "calcium": 10,
      "phosphorus": 20,
      "magnesium": 7,
      "iron": 0.36,
      "zinc": 0.07,
      "manganese": 0.071,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_07.webp"
    },
    {
      "id": "8",
      "cmnName": "Melon",
      "scfName": "Cucumis melo",
      "color1": Colors.yellow[100],
      "slDescription":
          "A melon is a large fruit which is sweet and juicy inside and has a hard green or yellow skin.",
      "description":
          """Melons originated in Africa or in the hot valleys of Southwest Asia, especially Iran and India. Melons are known to have been grown by the ancient Egyptians. Recent discoveries of melon seeds dated between 1350 and 1120 BC in Nuragic sacred wells have shown that melons were first brought to Europe by the Nuragic civilization of Sardinia during the Bronze Age.\n\nThe mature winter melon is a cooking vegetable that is widely used in Asia, especially in India. The immature melons are used as a culinary fruit (e.g., to make a distinctive fruit drink).\n\nIn 2018, world production of melons was 27 million tonnes, led by China with 46% of the total. Turkey, Iran, and India each produced more than 1 million tonnes.""",
      "imgUrl": "f_08.webp",
      "calories": 34,
      "carb": 8.16,
      "sugar": 7.86,
      "fiber": 0.9,
      "fat": 0.19,
      "protein": 0.84,
      "water": 90.2,
      "vitA": 0.169,
      "vitB1": 0.041,
      "vitB2": 0.019,
      "vitB3": 0.734,
      "vitB5": 0.105,
      "vitB6": 0.072,
      "vitB7": 0,
      "vitB9": 0.021,
      "vitB12": 0,
      "vitC": 36.7,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0.0025,
      "choline": 7.6,
      "potassium": 267,
      "chlorine": 0,
      "sodium": 16,
      "calcium": 9,
      "phosphorus": 15,
      "magnesium": 12,
      "iron": 0.21,
      "zinc": 0.18,
      "manganese": 0.041,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_08.webp"
    },
    {
      "id": "9",
      "cmnName": "Pineapple",
      "scfName": "Ananas comosus",
      "color1": Colors.amber[100],
      "slDescription":
          "Pineapple is a large tropical fruit with a spiky, tough skin and sweet insides. When European explorers came across it in South America in the 17th century, they called it a pineapple because of its pinecone appearance. The scaly bumps on the outside are called \"eyes.\" Slice it open, and you'll find bright yellow flesh that's both sweet and tart.",
      "description":
          """Pineapple is a tropical plant with an edible fruit indigenous to South America, where it has been cultivated for many centuries. The wild plant originates from the Paran\u00e1\u2013Paraguay River drainages between southern Brazil and Paraguay. Pineapple has been commercially grown in greenhouses and many tropical plantations. Iit is the third most important tropical fruit in world production.\n\nThe flesh and juice of the pineapple are used in cuisines around the world. In many tropical countries, pineapple is prepared and sold on roadsides as a snack.\n\nIn 2019, world production of pineapples was 28.2 million tonnes, led by Costa Rica, the Philippines, Brazil, and Indonesia as the largest producers.""",
      "imgUrl": "f_09.webp",
      "calories": 50,
      "carb": 13.12,
      "sugar": 9.85,
      "fiber": 1.4,
      "fat": 0.12,
      "protein": 0.54,
      "water": 86,
      "vitA": 0,
      "vitB1": 0.079,
      "vitB2": 0.032,
      "vitB3": 0.5,
      "vitB5": 0.213,
      "vitB6": 0.112,
      "vitB7": 0,
      "vitB9": 0.018,
      "vitB12": 0,
      "vitC": 47.8,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0,
      "choline": 5.5,
      "potassium": 109,
      "chlorine": 0,
      "sodium": 1,
      "calcium": 13,
      "phosphorus": 8,
      "magnesium": 12,
      "iron": 0.29,
      "zinc": 0.12,
      "manganese": 0.927,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_09.webp"
    },
    {
      "id": "10",
      "cmnName": "Plum",
      "scfName": "Prunus domestica",
      "color1": Colors.purple[100],
      "slDescription":
          "Plums are spherical and fleshy drupes of medium size, between 2 to 7 cm in diameter, of yellow, green or purple color, with a core containing an almond.",
      "description":
          """Plums may have been one of the first fruits domesticated by humans. Three of the most abundantly cultivated species are not found in the wild, only around human settlements in East European, Caucasian mountains and China. Mature plum fruits may have a dusty-white waxy coating that gives them a glaucous appearance. \n\nThe taste of the plum fruit ranges from sweet to tart; the skin itself may be particularly tart. It is juicy and can be eaten fresh or used in jam-making or other recipes. Plum juice can be fermented into plum wine. \n\nIn 2019, global production of plums (data combined with sloes) was 12.6 million tonnes, led by China with 56% of the world total""",
      "imgUrl": "f_10.webp",
      "calories": 46,
      "carb": 11.42,
      "sugar": 9.92,
      "fiber": 1.4,
      "fat": 0.28,
      "protein": 0.7,
      "water": 87,
      "vitA": 0.017,
      "vitB1": 0.028,
      "vitB2": 0.026,
      "vitB3": 0.417,
      "vitB5": 0.135,
      "vitB6": 0.029,
      "vitB7": 0,
      "vitB9": 0.005,
      "vitB12": 0,
      "vitC": 9.5,
      "vitD": 0,
      "vitE": 0.26,
      "vitK": 0.0064,
      "choline": 0,
      "potassium": 157,
      "chlorine": 0,
      "sodium": 0,
      "calcium": 6,
      "phosphorus": 16,
      "magnesium": 7,
      "iron": 0.17,
      "zinc": 0.1,
      "manganese": 0.052,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_10.webp"
    },
    {
      "id": "11",
      "cmnName": "Kiwi",
      "scfName": "Actinidia deliciosa",
      "color1": Colors.lightGreenAccent[100],
      "slDescription":
          "Kiwis are small fruits that pack a lot of flavor and plenty of health benefits. Their green flesh is sweet and tangy. It\u2019s also full of nutrients like vitamin C, vitamin K, vitamin E, folate, and potassium.",
      "description":
          """Kiwifruit is also known as Chinese Gooseberry. Kiwifruit is native to central and eastern China. The first recorded description of the kiwifruit dates to the 12th century during the Song dynasty. Cultivation of kiwifruit spread from China in the early 20th century to New Zealand, where the first commercial plantings occurred.\n\nKiwifruit may be eaten raw, made into juices, used in baked goods, prepared with meat or used as a garnish. The actinidain found in kiwifruit can be an allergen for some individuals, including children.\n\nIn 2018, global production of kiwifruit was 4 million tonnes, led by China with slightly more than half of the world total. Italy, New Zealand, Iran, Greece and Chile were other significant producers.""",
      "imgUrl": "f_11.webp",
      "calories": 63,
      "carb": 15.8,
      "sugar": 12.3,
      "fiber": 1.4,
      "fat": 0.28,
      "protein": 1.02,
      "water": 82,
      "vitA": 0.0024,
      "vitB1": 0,
      "vitB2": 0.074,
      "vitB3": 0.231,
      "vitB5": 0.12,
      "vitB6": 0.079,
      "vitB7": 0,
      "vitB9": 0.031,
      "vitB12": 8e-05,
      "vitC": 161.3,
      "vitD": 0,
      "vitE": 1.4,
      "vitK": 0.0061,
      "choline": 1.9,
      "potassium": 315,
      "chlorine": 0,
      "sodium": 3,
      "calcium": 17,
      "phosphorus": 25,
      "magnesium": 12,
      "iron": 0.21,
      "zinc": 0.08,
      "manganese": 0.048,
      "copper": 0.151,
      "selenium": 0.0004,
      "treeURL": "t_11.webp"
    },
    {
      "id": "12",
      "cmnName": "Watermelon",
      "scfName": "Citrullus lanatus",
      "color1": Colors.green[100],
      "slDescription":
          "he watermelon is a large fruit of a more or less spherical shape. It is usually eaten raw as table dessert. It has a sweet reddish or yellowish flesh. It is a very refreshing food that supplies very few calories. It also provides some vitamins and minerals.",
      "description":
          """Watermelon is grown in favorable climates from tropical to temperate regions worldwide for its large edible fruit. The fruit can be eaten raw or pickled, and the rind is edible after cooking. It may also be consumed as a juice or as an ingredient in mixed beverages.\n\nEvidence of the cultivation of watermelon in the Nile Valley has been found from the second millennium BC onward, and seeds of both species have been found at Twelfth Dynasty sites and in the tomb of Pharaoh Tutankhamun. Watermelons were cultivated for their high water content and were stored to be eaten during dry seasons, not only as a food source, but as a method of storing water.They are called as Xigua in China .\nIn 2017, global production of watermelons was 118 million tonnes, with China alone accounting for 67% of the total. Secondary producers included Iran, Turkey, and Brazil.""",
      "imgUrl": "f_12.webp",
      "calories": 30,
      "carb": 7.55,
      "sugar": 6.2,
      "fiber": 0.4,
      "fat": 0.15,
      "protein": 0.61,
      "water": 91.45,
      "vitA": 0.0028,
      "vitB1": 0.033,
      "vitB2": 0.021,
      "vitB3": 0.178,
      "vitB5": 0.221,
      "vitB6": 0.045,
      "vitB7": 0,
      "vitB9": 0,
      "vitB12": 0,
      "vitC": 8.1,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0,
      "choline": 4.1,
      "potassium": 112,
      "chlorine": 0,
      "sodium": 1,
      "calcium": 7,
      "phosphorus": 11,
      "magnesium": 10,
      "iron": 0.24,
      "zinc": 0.1,
      "manganese": 0.038,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_12.webp"
    },
    {
      "id": "13",
      "cmnName": "Guava",
      "scfName": "Psidium guajava",
      "color1": Colors.pink[100],
      "slDescription":
          "Guava is an incredibly delicious and nutritious tropical fruit. Low in calories and loaded with fibre, it is an excellent addition to a healthy diet. ",
      "description":
          """Guava is a common tropical fruit cultivated in many tropical and subtropical regions. Guavas originated from an area thought to extend from Mexico, Central America or northern South America throughout the Caribbean region. Archaeological sites in Peru yielded evidence of guava cultivation as early as 2500 BC.\n\nIn many countries, guava is eaten raw, typically cut into quarters or eaten like an apple; it is also eaten with a pinch of salt and pepper, cayenne powder or a mix of spices (masala). Because of its high level of pectin, guavas are used to make candies, preserves, jellies, jams, and marmalades.\n\nIn 2019, world production of guavas was 55 million tonnes, led by India with 45% of the total. Other major producers were China and Thailand.\n""",
      "imgUrl": "f_13.webp",
      "calories": 68,
      "carb": 14.32,
      "sugar": 8.92,
      "fiber": 5.4,
      "fat": 0.95,
      "protein": 2.55,
      "water": 81.2,
      "vitA": 0.0031,
      "vitB1": 0.067,
      "vitB2": 0.04,
      "vitB3": 1.084,
      "vitB5": 0.451,
      "vitB6": 0.11,
      "vitB7": 0,
      "vitB9": 0.0049,
      "vitB12": 0,
      "vitC": 228.3,
      "vitD": 0,
      "vitE": 0,
      "vitK": 2.2,
      "choline": 0,
      "potassium": 417,
      "chlorine": 0,
      "sodium": 2,
      "calcium": 18,
      "phosphorus": 40,
      "magnesium": 22,
      "iron": 0.26,
      "zinc": 0.23,
      "manganese": 0.15,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_13.webp"
    },
    {
      "id": "14",
      "cmnName": "Mango",
      "scfName": "Mangifera indica",
      "color1": Colors.orangeAccent[100],
      "slDescription":
          " Mangos are one of the most popular fruits in the world. They are the succulent, aromatic fruits of an evergreen tree (Mangifera indica), a member of the cashew family (Anacardiaceae) of flowering plants.\nBotanically, mango is a drupe, consisting of an outer skin, a fleshy edible portion, and a central stone enclosing a single seed \u2013 also called stone fruit, like a plum, cherry, or peach.",
      "description":
          """A mango is an edible stone fruit produced by the tropical tree which is believed to have originated from the region between northwestern Myanmar, Bangladesh, and northeastern India. It has been in cultivation since the ancient times resulting in two distinct types of modern mango cultivars: the \"Indian type\" and the \"Southeast Asian type\". \n\nMangoes are generally sweet, although the taste and texture of the flesh varies across cultivars; some, such as Alphonso, have a soft, pulpy, juicy texture similar to an overripe plum, while others, such as Tommy Atkins, are firmer, like a cantaloupe or avocado, with a fibrous texture.\n\nIn 2019, global production of mangoes (report includes mangosteens and guavas) was 56 million tonnes, led by India with 46% (26 million tonnes) of the world total""",
      "imgUrl": "f_14.webp",
      "calories": 60,
      "carb": 15,
      "sugar": 13.7,
      "fiber": 1.6,
      "fat": 0.38,
      "protein": 0.82,
      "water": 83.5,
      "vitA": 0.054,
      "vitB1": 0.028,
      "vitB2": 0.038,
      "vitB3": 0.669,
      "vitB5": 0.197,
      "vitB6": 0.119,
      "vitB7": 0,
      "vitB9": 0.0043,
      "vitB12": 0,
      "vitC": 36.4,
      "vitD": 0,
      "vitE": 0.0009,
      "vitK": 0.0042,
      "choline": 7.6,
      "potassium": 168,
      "chlorine": 0,
      "sodium": 1,
      "calcium": 11,
      "phosphorus": 14,
      "magnesium": 10,
      "iron": 0.16,
      "zinc": 0.09,
      "manganese": 0.063,
      "copper": 0.111,
      "selenium": 0.0006,
      "treeURL": "t_14.webp"
    },
    {
      "id": "15",
      "cmnName": "Apricot",
      "scfName": "Prunus armeniaca",
      "color1": Colors.amberAccent[100],
      "slDescription":
          "The apricot is a fruit that resembles the peach but much smaller, pale yellow or orange with some red shades. The pulp is not very juicy, it has fibre texture and farinaceous consistency when the apricot is mature.",
      "description":
          """The most commonly cultivated apricot was known in Armenia during ancient times, and has been cultivated there for so long that it was previously thought to have originated there. However, this is not supported by genetic studies, which instead confirm the hypothesis that domestication of apricot occurred in Central Asia and China.\n\nThe Chinese associate the apricot with education and medicine. Dried apricots are a type of traditional dried fruit. The world's largest producer of dried apricots is Turkey.\n\nIn 2019, world production of apricots was 4.1 million tonnes, led by Turkey with 21% of the world total. Other major producers (in descending order) were Uzbekistan, Iran, Italy, and Algeria.""",
      "imgUrl": "f_15.webp",
      "calories": 48,
      "carb": 11,
      "sugar": 9,
      "fiber": 2,
      "fat": 0.4,
      "protein": 1.4,
      "water": 86,
      "vitA": 0.096,
      "vitB1": 0.03,
      "vitB2": 0.04,
      "vitB3": 0.6,
      "vitB5": 0.24,
      "vitB6": 0.054,
      "vitB7": 0,
      "vitB9": 0.009,
      "vitB12": 0,
      "vitC": 10,
      "vitD": 0,
      "vitE": 0.89,
      "vitK": 0.0033,
      "choline": 0,
      "potassium": 259,
      "chlorine": 0,
      "sodium": 1,
      "calcium": 13,
      "phosphorus": 23,
      "magnesium": 10,
      "iron": 0.4,
      "zinc": 0.2,
      "manganese": 0.077,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_15.webp"
    },
    {
      "id": "16",
      "cmnName": "Cherry",
      "scfName": "Prunus avium",
      "color1": Colors.redAccent[100],
      "slDescription":
          "Cheery is a small roud fruit with a red skin, they are usually sweet and rich in vitamins K, A and C",
      "description":
          """The English word cherry derives from Old Northern French or Norman cherise from the Latin cerasum, referring to an ancient Greek region, Kerasous (\u039a\u03b5\u03c1\u03b1\u03c3\u03bf\u1fe6\u03c2) near Giresun, Turkey, from which cherries were first thought to be exported to Europe. Cherries arrived in North America early in the settlement of Brooklyn, New York (then called \"New Netherland\") when the region was under Dutch sovereignty.\n\nCherry wood is valued for its rich color and straight grain in manufacturing fine furniture, particularly desks, tables and chairs.\n\nIn 2014, world production of sweet cherries was 2.25 million tonnes, with Turkey producing 20% of this total. Other major producers of sweet cherries were the United States and Iran.""",
      "imgUrl": "f_16.webp",
      "calories": 63,
      "carb": 16,
      "sugar": 12.8,
      "fiber": 2.1,
      "fat": 0.2,
      "protein": 1.1,
      "water": 82,
      "vitA": 0.003,
      "vitB1": 0.027,
      "vitB2": 0.033,
      "vitB3": 0.154,
      "vitB5": 0.199,
      "vitB6": 0.049,
      "vitB7": 0,
      "vitB9": 0.004,
      "vitB12": 0,
      "vitC": 7,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0.0021,
      "choline": 6.1,
      "potassium": 222,
      "chlorine": 0,
      "sodium": 0,
      "calcium": 13,
      "phosphorus": 21,
      "magnesium": 11,
      "iron": 0.36,
      "zinc": 0.07,
      "manganese": 0.07,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_16.webp"
    },
    {
      "id": "17",
      "cmnName": "Coconut",
      "scfName": "Cocos nucifera",
      "color1": Colors.brown[200],
      "slDescription":
          "Coconut is a round and elongate fruit of white, fibrous and oily meat covered by a thick, brown and hairy shell. Coconuts are surrounded by a fibrous kernel, inside which is a white meat called copra. When the fruit is still tender it yields a milky fluid that is commonly used as basic food in some zones.",
      "description":
          """Coconuts were first domesticated by the Austronesian peoples in Island Southeast Asia and were spread during the Neolithic via their seaborne migrations as far east as the Pacific Islands, and as far west as Madagascar and the Comoros. They played a critical role in the long sea voyages of Austronesians by providing a portable source of food and water.\n\nThe name coconut is derived from the 16th-century Portuguese word coco, meaning 'head' or 'skull' after the three indentations on the coconut shell that resemble facial features. Mature, ripe coconuts can be used as edible seeds, or processed for oil and plant milk from the flesh, charcoal from the hard shell, and coir from the fibrous husk.\n\nIn 2019, world production of coconuts was 62 million tonnes, led by Indonesia, the Philippines, and India, with 75% combined of the total\n""",
      "imgUrl": "f_17.webp",
      "calories": 350,
      "carb": 15.23,
      "sugar": 6.23,
      "fiber": 9,
      "fat": 33.49,
      "protein": 3.33,
      "water": 47,
      "vitA": 0,
      "vitB1": 0.066,
      "vitB2": 0.02,
      "vitB3": 0.54,
      "vitB5": 0.3,
      "vitB6": 0.054,
      "vitB7": 0,
      "vitB9": 0.026,
      "vitB12": 0,
      "vitC": 3.3,
      "vitD": 0,
      "vitE": 0.24,
      "vitK": 0.0002,
      "choline": 0,
      "potassium": 356,
      "chlorine": 0,
      "sodium": 20,
      "calcium": 14,
      "phosphorus": 113,
      "magnesium": 32,
      "iron": 2.43,
      "zinc": 1.1,
      "manganese": 1.5,
      "copper": 0.435,
      "selenium": 0.0101,
      "treeURL": "t_17.webp"
    },
    {
      "id": "18",
      "cmnName": "Date",
      "scfName": "Phoenix dactylifera",
      "color1": Colors.lime[100],
      "slDescription":
          "The date is the fruit of the date palm. It is a berry of golden yellow colour or reddish-brown when ripe. Its meat is soft, aromatic and sweet, with a stone inside it of elongate shape and with a longitudinal furrow.",
      "description":
          """Dates have been a staple food of the Middle East and the Indus Valley for thousands of years. There is archaeological evidence of date cultivation in Arabia from the 6th millennium BCE. \n\nThe exact place of origin of date palm is uncertain because of long cultivation, according to some sources it probably originated from the Fertile Crescent region straddling Egypt and Mesopotamia, while others state that they are native to the Persian Gulf area or even western India. Fossil records show that the date palm has existed for at least 50 million years.\n\nDates are reported to have good potential in diabetes treatment due to the presence of polyphenols exerting strong antioxidant activities. The total annual world production of dates amounts to 8.5 million metric tons, countries of the Middle East and North Africa being the largest producers.""",
      "imgUrl": "f_18.webp",
      "calories": 282,
      "carb": 75.03,
      "sugar": 63.35,
      "fiber": 8,
      "fat": 0.39,
      "protein": 2.45,
      "water": 20.53,
      "vitA": 0.0001,
      "vitB1": 0.052,
      "vitB2": 0.066,
      "vitB3": 1.274,
      "vitB5": 0.589,
      "vitB6": 0.165,
      "vitB7": 0,
      "vitB9": 0.019,
      "vitB12": 0,
      "vitC": 0.4,
      "vitD": 0,
      "vitE": 0.05,
      "vitK": 0.0027,
      "choline": 0,
      "potassium": 656,
      "chlorine": 0,
      "sodium": 2,
      "calcium": 39,
      "phosphorus": 62,
      "magnesium": 43,
      "iron": 1.02,
      "zinc": 0.29,
      "manganese": 0.262,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_18.webp"
    },
    {
      "id": "19",
      "cmnName": "Lychee",
      "scfName": "Litchi chinensis",
      "color1": Colors.deepOrange[100],
      "slDescription":
          "The litchee is a round fruit, of 2.5-4cm of diameter, native to the east. It is red and the skin is rough. It has a white, sweet and juicy. It is usually eaten raw, although in China it is cooked with meat and fish. It is also used to prepare ice creams or milkshakes.",
      "description":
          """Lychee is a tropical tree native to the Guangdong and Fujian provinces of southeastern China, where cultivation is documented from the 11th century. Today, lychees are extensively grown in southern China, Taiwan, Vietnam and the rest of tropical Southeast Asia, the Indian Subcontinent, and in tropical regions of many other countries.\n\nLychee seeds contain methylene cyclopropyl glycine which can cause hypoglycemia associated with outbreaks of encephalopathy in undernourished Indian and Vietnamese children who had consumed lychee fruit.\n\nChina is the main producer of lychees, followed by India, other countries in Southeast Asia, the Indian Subcontinent, Madagascar and South Africa.""",
      "imgUrl": "f_19.webp",
      "calories": 66,
      "carb": 16.53,
      "sugar": 15.23,
      "fiber": 1.3,
      "fat": 0.44,
      "protein": 0.83,
      "water": 81.8,
      "vitA": 0,
      "vitB1": 0.011,
      "vitB2": 0.065,
      "vitB3": 0.603,
      "vitB5": 0,
      "vitB6": 0.1,
      "vitB7": 0,
      "vitB9": 0.014,
      "vitB12": 0,
      "vitC": 71.5,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0,
      "choline": 0,
      "potassium": 171,
      "chlorine": 0,
      "sodium": 1,
      "calcium": 5,
      "phosphorus": 31,
      "magnesium": 10,
      "iron": 0.13,
      "zinc": 0.07,
      "manganese": 0.055,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_19.webp"
    },
    {
      "id": "20",
      "cmnName": "Green Apple",
      "scfName": "Malus domestica",
      "color1": Colors.lightGreen[100],
      "slDescription":
          "Green apples have a pleasing light-green coloured skin with a sweet and sour taste. \u00b7 They contain more fiber, less carbohydrates and sugar than red apples.",
      "description":
          """The Granny Smith, the most common type of green apple is a tip-bearing apple variant which originated in Australia in 1868. It is named after Maria Ann Smith, who propagated the variant. \n\nIts acidity and strong taste makes it a frequent choice for both baking and for eating as a hand fruit. In 1968, the rock band The Beatles used an image of a Granny Smith apple as the logo for their corporation, Apple Corps Limited. For their record label, Apple Records, one side of vinyl albums featured the exterior of the fruit whilst the other side of the recording featured a cross-section of the apple.""",
      "imgUrl": "f_20.webp",
      "calories": 52,
      "carb": 13.81,
      "sugar": 10.39,
      "fiber": 2.4,
      "fat": 0.17,
      "protein": 0.26,
      "water": 85.7,
      "vitA": 0,
      "vitB1": 0.017,
      "vitB2": 0.026,
      "vitB3": 0.091,
      "vitB5": 0.061,
      "vitB6": 0.041,
      "vitB7": 0,
      "vitB9": 0.003,
      "vitB12": 0,
      "vitC": 4.6,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0,
      "choline": 0,
      "potassium": 107,
      "chlorine": 0,
      "sodium": 0,
      "calcium": 6,
      "phosphorus": 11,
      "magnesium": 5,
      "iron": 0.12,
      "zinc": 0.04,
      "manganese": 0,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_20.webp"
    },
    {
      "id": "21",
      "cmnName": "Black Currant",
      "scfName": "Ribes nigrum",
      "color1": Colors.deepPurple[100],
      "slDescription":
          "Black currants are berries that are native to central and northern Europe and Asia. These fruits are particularly consumed in Europe, especially due to their richness in vitamin C and bioactive compounds, such as phenolics, that are linked with potential health-promoting properties. ",
      "description":
          """Blackcurrant is native to temperate parts of central and northern Europe and northern Asia, where it prefers damp fertile soils. It is widely cultivated both commercially and domestically.\n\nThe blackcurrant is native to northern Europe and Asia. Cultivation in Europe is thought to have started around the last decades of the 17th century. During World War II, most fruits rich in vitamin C, such as oranges, became difficult to obtain in the United Kingdom. Since blackcurrant berries are a rich source of the vitamin, and blackcurrant plants are suitable for growing in the UK climate, the British Government encouraged their cultivation and soon the yield of the nation's crop increased significantly.\n\nThe leader in production is Russia (208,000 t), followed by Poland and Germany.""",
      "imgUrl": "f_21.webp",
      "calories": 63,
      "carb": 15.4,
      "sugar": 8.25,
      "fiber": 4.8,
      "fat": 0.4,
      "protein": 1.4,
      "water": 82,
      "vitA": 0,
      "vitB1": 0.05,
      "vitB2": 0.05,
      "vitB3": 0.3,
      "vitB5": 0.398,
      "vitB6": 0.066,
      "vitB7": 0,
      "vitB9": 0,
      "vitB12": 0,
      "vitC": 181,
      "vitD": 0,
      "vitE": 1,
      "vitK": 0,
      "choline": 0,
      "potassium": 322,
      "chlorine": 0,
      "sodium": 2,
      "calcium": 55,
      "phosphorus": 59,
      "magnesium": 24,
      "iron": 1.54,
      "zinc": 0.27,
      "manganese": 0.256,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_21.webp"
    },
    {
      "id": "22",
      "cmnName": "Blueberry",
      "scfName": "Vaccinium corymbosum",
      "color1": Colors.indigo[100],
      "slDescription":
          "Blueberries are tiny indigo-coloured edible berries, which are sweet to taste. Petite and both tart and sweet, these blueberries are the epitomy of what a blueberry should look and taste like. You can taste the richness and flavour in each delicious berry bite.",
      "description":
          """Blueberries\u2014both wild (lowbush) and cultivated (highbush)\u2014are all native to North America. The highbush varieties were introduced into Europe during the 1930s.\n\nBlueberries are sold fresh or are processed as individually quick frozen (IQF) fruit, pur\u00e9e, juice, or dried or infused berries. These may then be used in a variety of consumer goods, such as jellies, jams, pies, muffins, snack foods, or as an additive to breakfast cereals.\n\nIn 2019, world production of blueberries (lowbush and highbush combined) was 823,328 tonnes, led by the United States with 38% of global production and Canada with 21%.""",
      "imgUrl": "f_22.webp",
      "calories": 57,
      "carb": 14.49,
      "sugar": 9.96,
      "fiber": 2.4,
      "fat": 0.33,
      "protein": 0.74,
      "water": 84,
      "vitA": 0.015,
      "vitB1": 0.037,
      "vitB2": 0.041,
      "vitB3": 0.418,
      "vitB5": 0.124,
      "vitB6": 0.052,
      "vitB7": 0,
      "vitB9": 0.006,
      "vitB12": 0,
      "vitC": 9.7,
      "vitD": 0,
      "vitE": 0.57,
      "vitK": 0.0193,
      "choline": 0,
      "potassium": 77,
      "chlorine": 0,
      "sodium": 1,
      "calcium": 6,
      "phosphorus": 12,
      "magnesium": 6,
      "iron": 0.28,
      "zinc": 0.165,
      "manganese": 0.336,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_22.webp"
    },
    {
      "id": "23",
      "cmnName": "Cranberry",
      "scfName": "Vaccinium erythrocarpum",
      "color1": Colors.red[100],
      "slDescription":
          "As popular as its juice, cranberry are soft bright red berries giving a sweet sour taste and perfect berry benefits. Cranberries are round, elongated fruits that measure in size from 1.5 to 3 centimeters. They grow on low, bushy, trailing vines with oval leaves, and take about 16 months to mature. Their skins ripen from green to white, then to a glossy, scarlet red. ",
      "description":
          """The name cranberry derives from the German kraanbere (English translation, craneberry), first named as cranberry in English by the missionary John Eliot in 1647. In North America, the Narragansett people of the Algonquian nation in the regions of New England appeared to be using cranberries in pemmican for food and for dye. \n\nAs fresh cranberries are hard, sour, and bitter, about 95% of cranberries are processed and used to make cranberry juice and sauce. They are also sold dried and sweetened. Cranberry juice is usually sweetened or blended with other fruit juices to reduce its natural tartness. \n\nIn 2019, world production of cranberry was 687,534 tonnes, mainly by the United States, Canada, and Chile, which collectively accounted for 97% of the global total.""",
      "imgUrl": "f_23.webp",
      "calories": 46,
      "carb": 12,
      "sugar": 4.3,
      "fiber": 3.6,
      "fat": 0.1,
      "protein": 0.5,
      "water": 87,
      "vitA": 0,
      "vitB1": 0.012,
      "vitB2": 0.02,
      "vitB3": 0.101,
      "vitB5": 0.295,
      "vitB6": 0.057,
      "vitB7": 0,
      "vitB9": 0.001,
      "vitB12": 0,
      "vitC": 14,
      "vitD": 0,
      "vitE": 1.3,
      "vitK": 0.005,
      "choline": 0,
      "potassium": 80,
      "chlorine": 0,
      "sodium": 2,
      "calcium": 8,
      "phosphorus": 11,
      "magnesium": 6,
      "iron": 0.2,
      "zinc": 0.1,
      "manganese": 0.36,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_23.webp"
    },
    {
      "id": "24",
      "cmnName": "Gooseberry",
      "scfName": "Ribes uva-crispa",
      "color1": Colors.lime[100],
      "slDescription":
          "Gooseberry/Amla are small, round berries with light-green skin. The skin is almost translucent, with 6 to 8 faint yellow striations, making the Amla appear to be segmented. The skin is tough, yet thin with a flesh that is crisp and juicy with a taste both sour and bitter. The flesh of an Amla is also somewhat astringent. In the center of the berry lies a hexagonal-shaped stone with 6 small seeds.",
      "description":
          """The gooseberry is indigenous to many parts of Europe and western Asia, growing naturally in alpine thickets and rocky woods in the lower country, from France eastward, well into the Himalayas and peninsular India.\n\nGooseberries are edible and can be eaten raw, or cooked as an ingredient in desserts, such as pies, fools and crumbles. Early pickings are generally sour and more appropriate for culinary use. Gooseberries are also used to flavor beverages such as sodas, flavored waters, or milk, and can be made into fruit wines and teas. Nutritionally, gooseberries are a rich source of vitamin C.\n\nIndonesia is the largest producer of gooseberry, followed by Philippines, India and Brazil. """,
      "imgUrl": "f_24.webp",
      "calories": 44,
      "carb": 10.18,
      "sugar": 5.1,
      "fiber": 4.3,
      "fat": 0.88,
      "protein": 0.015,
      "water": 0.04,
      "vitA": 0.03,
      "vitB1": 0.3,
      "vitB2": 0.286,
      "vitB3": 0.08,
      "vitB5": 0,
      "vitB6": 0.006,
      "vitB7": 0,
      "vitB9": 0.006,
      "vitB12": 0,
      "vitC": 27.7,
      "vitD": 0,
      "vitE": 0.37,
      "vitK": 0,
      "choline": 0,
      "potassium": 198,
      "chlorine": 0,
      "sodium": 1,
      "calcium": 25,
      "phosphorus": 27,
      "magnesium": 10,
      "iron": 0.31,
      "zinc": 0.12,
      "manganese": 0.144,
      "copper": 0.007,
      "selenium": 0,
      "treeURL": "t_24.webp"
    },
    {
      "id": "25",
      "cmnName": "Pomegranate",
      "scfName": "Punica granatum",
      "color1": Colors.redAccent[100],
      "slDescription":
          "Ranging in color from deep magenta to bright red, the spherical fruits are roughly the size of an apple and have a thin but tough, leathery skin. The interior of the fruit is filled with seeds, technically called arils. 1 Piece weighs around 250 to 350 Grams",
      "description":
          """The name pomegranate derives from medieval Latin p\u014dmum \"apple\" and gr\u0101n\u0101tum \"seeded\". Ancient Egyptians regarded the pomegranate as a symbol of prosperity and ambition. The French term for pomegranate, grenade, has given its name to the military grenade.\n\nThe pomegranate is native to a region from modern-day Iran to northern India. Pomegranates have been cultivated throughout the Middle East, South Asia, and Mediterranean region for several millennia, and it is also cultivated in the Central Valley of California and in Arizona. Pomegranates may have been domesticated as early as the fifth millennium BC, as they were one of the first fruit trees to be domesticated in the eastern Mediterranean region. \n\nAt the global level, India is the world's largest producer of pomegranates, followed by Iran.""",
      "imgUrl": "f_25.webp",
      "calories": 83,
      "carb": 18.7,
      "sugar": 13.67,
      "fiber": 4,
      "fat": 1.17,
      "protein": 1.67,
      "water": 78,
      "vitA": 0,
      "vitB1": 0.067,
      "vitB2": 0.053,
      "vitB3": 0.293,
      "vitB5": 0.377,
      "vitB6": 0.075,
      "vitB7": 0,
      "vitB9": 0.038,
      "vitB12": 0,
      "vitC": 10.2,
      "vitD": 0,
      "vitE": 0.6,
      "vitK": 0.0164,
      "choline": 7.6,
      "potassium": 236,
      "chlorine": 7.6,
      "sodium": 3,
      "calcium": 10,
      "phosphorus": 36,
      "magnesium": 12,
      "iron": 0.3,
      "zinc": 0.35,
      "manganese": 0.119,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_25.webp"
    },
    {
      "id": "26",
      "cmnName": "Muskmelon",
      "scfName": "Cucumis melo",
      "color1": Colors.amber[100],
      "slDescription":
          "Musk Melons vary in shape in size and tend to weigh between 5 and 8 pounds. Most are round to ovate and some will have a slightly squat shape. They have a pronounced light tan netting over their exterior, a characteristic unique to all Musk Melon varieties. 1 Piece weighs around 750 to 850 Grams",
      "description":
          """The muskmelon is an annual, trailing herb. It grows well in subtropical or warm, temperate climates. Melons prefer warm, well-fertilized soil with good drainage that is rich in nutrients.\n\nThe origin of muskmelons is not known. Research has revealed that seeds and rootstocks were among the goods traded along the caravan routes of the Ancient World. Some botanists consider melons native to the Levant and Egypt, while others place their origin in Iran, India or Central Asia.\n\nChina is the largest producer of muskmelon, followed by Turkey, Iran and Egypt.""",
      "imgUrl": "f_26.webp",
      "calories": 34,
      "carb": 8.16,
      "sugar": 7.86,
      "fiber": 0.9,
      "fat": 0.19,
      "protein": 0.84,
      "water": 90.2,
      "vitA": 0.169,
      "vitB1": 0.041,
      "vitB2": 0.019,
      "vitB3": 0.734,
      "vitB5": 0.105,
      "vitB6": 0.072,
      "vitB7": 0,
      "vitB9": 0.021,
      "vitB12": 0,
      "vitC": 36.7,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0.0025,
      "choline": 7.6,
      "potassium": 267,
      "chlorine": 0,
      "sodium": 16,
      "calcium": 9,
      "phosphorus": 15,
      "magnesium": 12,
      "iron": 0.21,
      "zinc": 0.18,
      "manganese": 0.041,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_26.webp"
    },
    {
      "id": "27",
      "cmnName": "Blackberry",
      "scfName": "Rubus ursinus",
      "color1": Colors.deepPurple[100],
      "slDescription":
          "The blackberry is an aggregate fruit that is composed of many smaller fruits called drupes. The fruit is very dark purple with smooth, fragile skin.",
      "description":
          """One of the earliest known instances of blackberry consumption comes from Denmark approximately 2,500 years ago. Blackberry plants were used for traditional medicine by Greeks, other European peoples, and aboriginal Americans. A 1771 document described brewing blackberry leaves, stem, and bark for stomach ulcers.\n\nFolklore in the United Kingdom and Ireland tells that blackberries should not be picked after Old Michaelmas Day (11 October) as the devil (or a P\u00faca) has made them unfit to eat by stepping, spitting or fouling on them. Blackberry leaves are food for certain caterpillars; some grazing mammals, especially deer, are also very fond of the leaves.""",
      "imgUrl": "f_27.webp",
      "calories": 43,
      "carb": 9.61,
      "sugar": 4.88,
      "fiber": 5.3,
      "fat": 0.49,
      "protein": 1.39,
      "water": 88.4,
      "vitA": 0.063,
      "vitB1": 0.02,
      "vitB2": 0.026,
      "vitB3": 0.646,
      "vitB5": 0,
      "vitB6": 0.03,
      "vitB7": 0,
      "vitB9": 0.025,
      "vitB12": 0,
      "vitC": 21,
      "vitD": 0,
      "vitE": 1.17,
      "vitK": 0.0198,
      "choline": 0,
      "potassium": 162,
      "chlorine": 0,
      "sodium": 1,
      "calcium": 29,
      "phosphorus": 22,
      "magnesium": 20,
      "iron": 0.062,
      "zinc": 0.53,
      "manganese": 0,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_27.webp"
    },
    {
      "id": "28",
      "cmnName": "Custard Apple",
      "scfName": "Annona reticulata",
      "color1": Colors.amberAccent[100],
      "slDescription":
          "Custard apples also called Sugar apple , is spherical-conical fruit with knobby segments and black seeds.The custard apple is a fruit of tropical origin, more or less round-shaped and netted green skin, consumed for its white, sweet and very aromatic pulp. It is usually eaten raw, although they are also used in jams, milkshakes or ice creams. It is rich in vitamins and minerals.",
      "description":
          """Custard apple vary in shape, heart-shaped, spherical, oblong or irregular. The flesh varies from juicy and very aromatic to hard with an astringent taste. The flavor is sweet and pleasant, akin to the taste of 'traditional' custard. The custard apple is native to the Americas, but has been found on the island of Timor as early as 1000 CE.\n\nFruits are dark greening brown in colour and marked with depressions giving it a quilted appearance; its pulp is reddish yellow, sweetish, and very soft (hence the common name); the kernels of the seeds are said to be poisonous.\n\nCustard apples common in China, Phillippines, Egypt and Central Africa and India.""",
      "imgUrl": "f_28.webp",
      "calories": 94,
      "carb": 23.64,
      "sugar": 18.1,
      "fiber": 4.4,
      "fat": 0.29,
      "protein": 2.06,
      "water": 74,
      "vitA": 0,
      "vitB1": 0.11,
      "vitB2": 0.113,
      "vitB3": 0.883,
      "vitB5": 0.226,
      "vitB6": 0.2,
      "vitB7": 0,
      "vitB9": 0.014,
      "vitB12": 0,
      "vitC": 36.3,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0,
      "choline": 0,
      "potassium": 247,
      "chlorine": 0,
      "sodium": 9,
      "calcium": 24,
      "phosphorus": 32,
      "magnesium": 21,
      "iron": 0.6,
      "zinc": 0.1,
      "manganese": 0.42,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_28.webp"
    },
    {
      "id": "29",
      "cmnName": "Strawberry",
      "scfName": "Fragaria \u00d7 ananassa",
      "color1": Colors.pink[100],
      "slDescription":
          "The strawberry is a succulent and fragrant fruit of bright red colour, obtained from the plant with the same name. In the West it is considered as the \" queen of the fruit\". It is eaten raw and used to make jam, stewed fruit",
      "description":
          """Strawberry is widely appreciated for its characteristic aroma, bright red color, juicy texture, and sweetness. It is consumed in large quantities, either fresh or in such prepared foods as jam, juice, pies, ice cream, milkshakes, and chocolates. \n\nThe first garden strawberry was grown in Brittany, France, during the late 18th century. Prior to this, wild strawberries and cultivated selections from wild strawberry species were the common source of the fruit. The strawberry fruit was mentioned in ancient Roman literature in reference to its medicinal use. The French began taking the strawberry from the forest to their gardens for harvest in the 14th century.\n\nIn 2019, world production of strawberries was 8.9 million tonnes, led by China with 40% of the total, and the United States and Mexico as other significant producers""",
      "imgUrl": "f_29.webp",
      "calories": 33,
      "carb": 7.68,
      "sugar": 4.89,
      "fiber": 2,
      "fat": 0.3,
      "protein": 0.67,
      "water": 90.95,
      "vitA": 0,
      "vitB1": 0.024,
      "vitB2": 0.022,
      "vitB3": 0.386,
      "vitB5": 0.125,
      "vitB6": 0.047,
      "vitB7": 0,
      "vitB9": 0.024,
      "vitB12": 0,
      "vitC": 58.8,
      "vitD": 0,
      "vitE": 0.29,
      "vitK": 0.0022,
      "choline": 5.7,
      "potassium": 154,
      "chlorine": 0,
      "sodium": 1,
      "calcium": 16,
      "phosphorus": 24,
      "magnesium": 13,
      "iron": 0.41,
      "zinc": 0.14,
      "manganese": 0.386,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_29.webp"
    },
    {
      "id": "30",
      "cmnName": "Vanilla",
      "scfName": "Vanilla planifolia",
      "color1": Colors.blueGrey[100],
      "slDescription":
          "Vanilla is a spice derived from orchids of the genus Vanilla, primarily obtained from pods of the Mexican species, flat-leaved vanilla (V. planifolia).Vanilla is a stunningly complex and subtle spice, containing at a guess somewhere between 250 and 500 different flavor and fragrance components.",
      "description":
          """The word vanilla, derived from vainilla, the diminutive of the Spanish word vaina (vaina itself meaning a sheath or a pod), is translated simply as \"little pod\". Pre-Columbian Mesoamerican people cultivated the vine of the vanilla orchid, called tl\u012blxochitl by the Aztecs.\n\nRegarded as the world's most popular aroma and flavor, vanilla is a widely used aroma and flavor compound for foods, beverages and cosmetics, as indicated by its popularity as an ice cream flavor. Although vanilla is a prized flavoring agent on its own, it is also used to enhance the flavor of other substances, to which its own flavor is often complementary, such as chocolate, custard, caramel, coffee, and others. Vanilla is a common ingredient in Western sweet baked goods, such as cookies and cakes\n\nIn 2018, world production of vanilla was 7,575 tonnes, led by Madagascar with 41.0% of the total, and Indonesia with 29.8%.""",
      "imgUrl": "f_30.webp",
      "calories": 288,
      "carb": 12.65,
      "sugar": 12.65,
      "fiber": 0,
      "fat": 0.06,
      "protein": 0.06,
      "water": 87.1,
      "vitA": 0,
      "vitB1": 0,
      "vitB2": 0.095,
      "vitB3": 0.425,
      "vitB5": 0.035,
      "vitB6": 0.026,
      "vitB7": 0,
      "vitB9": 0,
      "vitB12": 0,
      "vitC": 0,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0,
      "choline": 0,
      "potassium": 148,
      "chlorine": 0,
      "sodium": 9,
      "calcium": 11,
      "phosphorus": 6,
      "magnesium": 12,
      "iron": 0.12,
      "zinc": 0.11,
      "manganese": 0.23,
      "copper": 0.072,
      "selenium": 0,
      "treeURL": "t_30.webp"
    },
    {
      "id": "31",
      "cmnName": "Jackfruit",
      "scfName": "Artocarpus heterophyllus",
      "color1": Colors.lightGreenAccent[100],
      "slDescription":
          "Jackfruit is the largest tree-borne fruit in the world, reaching up to 60 cm (about 2 feet) long and weighing up to 18 kg (about 40 pounds). It is ellipsoidal and aggregate, composed of multiple \u201cbulbs\u201d of seed-containing flesh around a stringy core, all of which is enclosed by a bumpy rind",
      "description":
          """Jackfruit is commonly used in South and Southeast Asian cuisines. Both ripe and unripe fruits are consumed. It is available internationally canned or frozen and in chilled meals as are various products derived from the fruit such as noodles and chips.\n\nThe jackfruit has played a significant role in Indian agriculture for centuries. Archaeological findings in India have revealed that jackfruit was cultivated in India 3000 to 6000 years ago. The jackfruit is the national fruit of Bangladesh and Sri Lanka.\n\nIn 2017, India produced 1.4 million tonnes of jackfruit, followed by Bangladesh, Thailand, and Indonesia.\n""",
      "imgUrl": "f_31.webp",
      "calories": 95,
      "carb": 23.25,
      "sugar": 19.08,
      "fiber": 1.5,
      "fat": 0.64,
      "protein": 1.72,
      "water": 73.5,
      "vitA": 0.005,
      "vitB1": 0.105,
      "vitB2": 0.055,
      "vitB3": 0.92,
      "vitB5": 0.235,
      "vitB6": 0.329,
      "vitB7": 0,
      "vitB9": 0.024,
      "vitB12": 0,
      "vitC": 13.8,
      "vitD": 0,
      "vitE": 0.34,
      "vitK": 0,
      "choline": 0,
      "potassium": 448,
      "chlorine": 0,
      "sodium": 2,
      "calcium": 24,
      "phosphorus": 21,
      "magnesium": 29,
      "iron": 0.23,
      "zinc": 0.13,
      "manganese": 0.043,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_31.webp"
    },
    {
      "id": "32",
      "cmnName": "Tamarind",
      "scfName": "Tamarindus indica",
      "color1": Colors.brown[100],
      "slDescription":
          "Tamarind is a tree. The tamarind tree produces brown, pod-like fruits that contain a sweet, tangy pulp, which is used in cuisines around the world.",
      "description":
          """Tamarind is a leguminous tree bearing edible fruit that is indigenous to tropical Africa. \n\nThe tamarind tree produces brown, pod-like fruits that contain a sweet, tangy pulp, which is used in cuisines around the world. The pulp is also used in traditional medicine and as a metal polish. The tree's wood can be used for woodworking and tamarind seed oil can be extracted from the seeds. Tamarind's tender young leaves are used in Indian and Filipino cuisine.\n\nIn hens, tamarind has been found to lower cholesterol in their serum, and in the yolks of the eggs they laid. Due to a lack of available human clinical trials, there is insufficient evidence to recommend tamarind for the treatment of hypercholesterolemia or diabetes.\n\n\n""",
      "imgUrl": "f_32.webp",
      "calories": 240,
      "carb": 62.5,
      "sugar": 57.4,
      "fiber": 5.1,
      "fat": 0.6,
      "protein": 2.8,
      "water": 31.4,
      "vitA": 0.009,
      "vitB1": 0.428,
      "vitB2": 0.152,
      "vitB3": 1.938,
      "vitB5": 0.143,
      "vitB6": 0.066,
      "vitB7": 0,
      "vitB9": 0.014,
      "vitB12": 0,
      "vitC": 3.5,
      "vitD": 0,
      "vitE": 0.1,
      "vitK": 0.0028,
      "choline": 8.6,
      "potassium": 628,
      "chlorine": 0,
      "sodium": 28,
      "calcium": 74,
      "phosphorus": 113,
      "magnesium": 92,
      "iron": 2.8,
      "zinc": 0.1,
      "manganese": 0,
      "copper": 0.86,
      "selenium": 0.0013,
      "treeURL": "t_32.webp"
    },
    {
      "id": "33",
      "cmnName": "Elderberry ",
      "scfName": "Sambucus nigra",
      "color1": Colors.indigo[100],
      "slDescription":
          "Elderberry is the dark purple berry from the European elder tree. ",
      "description":
          """The Common elderberry, is a species of elderberry native to a large area of North America east of the Rocky Mountains, south to Bolivia.It grows in a variety of conditions including both wet and dry soils, primarily in sunny locations.\n\nElderberries are a small black fruit, they are toxic/poisonous when consumed directly , though cooked berries (pulp and skin) of most species of Sambucus are edible.Traditional methods of consuming elderberry includes jams, jellies, and syrups, all of which cook down the fruit and strain out the seeds.\n\nElderberries are rich in anthocyanidins  that combine to give elderberry juice an intense blue-purple coloration and are thus used as colorants in various products.\n""",
      "imgUrl": "f_33.webp",
      "calories": 73,
      "carb": 18.4,
      "sugar": 10,
      "fiber": 7,
      "fat": 0.5,
      "protein": 0.66,
      "water": 79.8,
      "vitA": 0.03,
      "vitB1": 0.07,
      "vitB2": 0.06,
      "vitB3": 0.5,
      "vitB5": 0.14,
      "vitB6": 0.23,
      "vitB7": 0,
      "vitB9": 0.006,
      "vitB12": 0,
      "vitC": 36,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0,
      "choline": 0,
      "potassium": 280,
      "chlorine": 0,
      "sodium": 0,
      "calcium": 38,
      "phosphorus": 39,
      "magnesium": 5,
      "iron": 1.6,
      "zinc": 0.11,
      "manganese": 0,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_33.webp"
    },
    {
      "id": "34",
      "cmnName": "Fig",
      "scfName": "Ficus carica",
      "color1": Colors.yellow[100],
      "slDescription":
          "Figs are a unique fruit resembling a teardrop. They're about the size of your thumb, filled with hundreds of tiny seeds, and have an edible purple or green peel. The flesh of the fruit is pink and has a mild, sweet taste.",
      "description":
          """The fig is the edible fruit of Ficus carica, Native to the Mediterranean and western Asia, it has been cultivated since ancient times and is now widely grown throughout the world, both for its fruit and as an ornamental plant.There are over 800 subspecies of figs.\n\nFigs can be eaten fresh or dried, or processed into jam, rolls, biscuits and other types of desserts. Since the ripe fruit does not transport and keep well, most commercial production is in dried and processed forms. Raw figs contain roughly 80% water and 20% carbohydrates, with negligible protein, fat and micronutrient content. They are a moderate source of dietary fiber.\n\nIn 2018, world production of raw figs was 1.14 million tonnes, led by Turkey and North African countries (Egypt, Morocco, and Algeria) as the largest producers, collectively accounting for 64% of the total.\nThe edible fig is one of the first plants that were cultivated by humans. Nine subfossil figs of a parthenocarpic (and therefore self-pollinating) type dating to about 9400\u20139200 BC were found in the early Neolithic village Gilgal I (in the Jordan Valley, 13 km north of Jericho). \n""",
      "imgUrl": "f_34.webp",
      "calories": 74,
      "carb": 19.2,
      "sugar": 16.3,
      "fiber": 3,
      "fat": 0.3,
      "protein": 0.8,
      "water": 79,
      "vitA": 0.007,
      "vitB1": 0.06,
      "vitB2": 0.05,
      "vitB3": 0.4,
      "vitB5": 0.3,
      "vitB6": 0.1,
      "vitB7": 0,
      "vitB9": 0.006,
      "vitB12": 0,
      "vitC": 2,
      "vitD": 0,
      "vitE": 0.11,
      "vitK": 0.0047,
      "choline": 0,
      "potassium": 232,
      "chlorine": 0,
      "sodium": 1,
      "calcium": 35,
      "phosphorus": 14,
      "magnesium": 17,
      "iron": 0.4,
      "zinc": 0.15,
      "manganese": 0.13,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_34.webp"
    },
    {
      "id": "35",
      "cmnName": "Horned Melon",
      "scfName": "Cucumis metuliferus",
      "color1": Colors.lightGreenAccent[100],
      "slDescription":
          "Horned Melon / Kiwanos are oval shaped fruits with pronounced spiky points all over.  They are yellow or orange, and about 4 or 5 inches long.  Inside they are super seedy, with a bright emerald green very liquidy flesh surrounding the seeds.",
      "description":
          """Cucumis metuliferus, commonly called the African horned cucumber, horned melon, spiked melon, jelly melon, kiwano, or cuke-a-saurus is an annual vine in the cucumber and melon family, Cucurbitaceae.\n\nIts fruit has horn-like spines, hence the name \"horned melon\". The ripe fruit has orange skin and lime green, jelly-like flesh. It is native to Southern Africa.It is found in South Africa, Namibia, Botswana, Zambia, Zimbabwe, Mozambique, and Angola.\n\nIt is one of the few sources of water during the dry season in the Kalahari Desert.In northern Zimbabwe it is called gaka or gakachika,[5] and is primarily used as a snack or salad, and rarely for decoration. It can be eaten at any stage of ripening, but when overripe, it will burst forcefully to release seeds.\nThe fruit's taste has been compared to a combination of banana and passionfruit or a combination of banana, cucumber and lime. A small amount of salt or sugar can increase the flavor but the seed content can make eating the fruit less convenient than many common fruits.\n""",
      "imgUrl": "f_35.webp",
      "calories": 44,
      "carb": 7.56,
      "sugar": 0,
      "fiber": 0,
      "fat": 1.26,
      "protein": 1.78,
      "water": 88.97,
      "vitA": 0.007,
      "vitB1": 0.025,
      "vitB2": 0.015,
      "vitB3": 0.565,
      "vitB5": 0.183,
      "vitB6": 0.063,
      "vitB7": 0,
      "vitB9": 0.003,
      "vitB12": 0,
      "vitC": 5.3,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0,
      "choline": 0,
      "potassium": 123,
      "chlorine": 0,
      "sodium": 2,
      "calcium": 13,
      "phosphorus": 37,
      "magnesium": 40,
      "iron": 1.13,
      "zinc": 0.48,
      "manganese": 0.039,
      "copper": 0.02,
      "selenium": 0,
      "treeURL": "t_35.webp"
    },
    {
      "id": "36",
      "cmnName": "Ice Cream Bean",
      "scfName": "Inga edulis",
      "color1": Colors.blueGrey[100],
      "slDescription":
          "Ice cream beans are legumes, just like the beans you grow in your vegetable garden. The pods are about a foot long and contain beans about the size of limas surrounded by a sweet, cottony pulp. The pulp has a flavor similar to vanilla ice cream, hence its name.",
      "description":
          """Inga edulis, known as ice cream-bean, joaquiniquil, cuaniquil, guama or guaba, is a fruit native to South America.It is widely grown, especially by Indigenous Amazonians, for shade, food, timber, medicine, and production of the alcoholic beverage cachiri. It is popular in Peru, Ecuador, Pernambuco-Brazil, Venezuela and Colombia.[\n\n The common name \"ice-cream bean\" alludes to the sweet flavor and smooth texture of the pulp.The ice cream bean doesn't need to be cooked, the ice cream bean can just be eaten provided that the bean has been ripe. In South America, we can easily find the ice cream bean tree planted in the edge of the street and function as the shadowing tree. The tree can grow up to 60 feet while the bean pea fruit can be up to 1 meter.\n""",
      "imgUrl": "f_36.webp",
      "calories": 60,
      "carb": 15.5,
      "sugar": 0,
      "fiber": 1.2,
      "fat": 0.1,
      "protein": 0.1,
      "water": 0,
      "vitA": 0,
      "vitB1": 0,
      "vitB2": 0,
      "vitB3": 0,
      "vitB5": 0,
      "vitB6": 0,
      "vitB7": 0,
      "vitB9": 0,
      "vitB12": 0,
      "vitC": 0,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0,
      "choline": 0,
      "potassium": 0,
      "chlorine": 0,
      "sodium": 0,
      "calcium": 0,
      "phosphorus": 0,
      "magnesium": 0,
      "iron": 0,
      "zinc": 0,
      "manganese": 0,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_36.webp"
    },
    {
      "id": "37",
      "cmnName": "Nutmeg",
      "scfName": "Myristica fragrans",
      "color1": Colors.brown[100],
      "slDescription":
          "Nutmeg is a spice made from the seed of the nutmeg tree (Myristica fragrant), a native Indonesian evergreen tree that is the source of two popular spices: nutmeg and mace. Nutmeg is the inner seed, while mace is the red, lace-like substance that covers the seed.",
      "description":
          """Nutmeg is the spice made by grinding the seed of the fragrant nutmeg (Myristica fragrans) tree into powder. The spice has a distinctive pungent fragrance and a warm slightly sweet taste; it is used to flavor many kinds of baked goods, confections, puddings, potatoes, meats, sausages, sauces, vegetables, and such beverages as eggnog.\n\nThe seeds are dried gradually in the sun over a period of six to eight weeks. During this time the nutmeg shrinks away from its hard seed coat until the kernels rattle in their shells when shaken. The shell is then broken with a wooden club and the nutmegs are picked out. Dried nutmegs are grayish brown ovals with furrowed surfaces\n\nThe earliest evidence of nutmeg usage comes in the form of 3,500 year old potsherd residues from the island of Pulau Ai, one of the Banda Islands in eastern Indonesia.\n The national flag of Grenada, adopted in 1974, shows a stylised split-open nutmeg fruit as it was a primary export. In 2019, global production of nutmeg was 142,000 tonnes, led by Indonesia, Guatemala, and India, having 38,000 to 43,000 tonnes each and a combined 85% of the world total.\n""",
      "imgUrl": "f_37.webp",
      "calories": 37,
      "carb": 49.29,
      "sugar": 2.99,
      "fiber": 20.8,
      "fat": 36.31,
      "protein": 5.84,
      "water": 6.23,
      "vitA": 0.005,
      "vitB1": 0,
      "vitB2": 0,
      "vitB3": 0,
      "vitB5": 0,
      "vitB6": 0.16,
      "vitB7": 0,
      "vitB9": 0,
      "vitB12": 0,
      "vitC": 3,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0,
      "choline": 0,
      "potassium": 350,
      "chlorine": 0,
      "sodium": 16,
      "calcium": 184,
      "phosphorus": 213,
      "magnesium": 183,
      "iron": 3.04,
      "zinc": 2.15,
      "manganese": 2.9,
      "copper": 1.027,
      "selenium": 0.0016,
      "treeURL": "t_37.webp"
    },
    {
      "id": "38",
      "cmnName": "Quince",
      "scfName": "Cydonia oblonga",
      "color1": Colors.yellow[100],
      "slDescription":
          "A quince is a fruit of contradictions. It's generally too astringent to eat raw, yet it smells so guava-sweet. Its white, dry, hard flesh blushes and softens, without turning mushy, when cooked. It has tough, waxy skin that bruises more easily than you'd think.",
      "description":
          """It is a tree fruit that bears a deciduous pome fruit, similar in appearance to a pear, and is bright golden-yellow when mature. The raw fruit is a source of food. The tree has been grown by landscape architects for its attractive pale pink blossoms and other ornamental qualities.\n\nQuince is a hardy, drought-tolerant shrub which adapts to many soils of low to medium pH. It tolerates both shade and sun, but sunlight is required to produce larger flowers and ensure fruit ripening.Quince is cultivated on all continents in warm-temperate and temperate climates. It requires a cooler period of the year, with temperatures under 7 \u00b0C (45 \u00b0F), to flower properly.\n\nSome varieties of quince, such as 'Aromatnaya' and 'Kuganskaya' do not require cooking and can be eaten raw. However, most varieties of quince are too hard, astringent and sour to eat raw unless \"bletted\" (softened by frost and subsequent decay). High in pectin, they are used to make jam, jelly and quince pudding, or they may be peeled, then roasted, baked or stewed; pectin levels diminish as the fruit ripens. The flesh of the fruit turns red after a long cooking with sugar by formation of anthocyanins. The very strong perfume means they can be added in small quantities to apple pies and jam to enhance the flavor. \n""",
      "imgUrl": "f_38.webp",
      "calories": 57,
      "carb": 15.3,
      "sugar": 0,
      "fiber": 1.9,
      "fat": 0.1,
      "protein": 0.4,
      "water": 84,
      "vitA": 0,
      "vitB1": 0.02,
      "vitB2": 0.03,
      "vitB3": 0.2,
      "vitB5": 0.081,
      "vitB6": 0.04,
      "vitB7": 0,
      "vitB9": 0.003,
      "vitB12": 0,
      "vitC": 15,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0,
      "choline": 0,
      "potassium": 197,
      "chlorine": 0,
      "sodium": 4,
      "calcium": 11,
      "phosphorus": 17,
      "magnesium": 8,
      "iron": 0.7,
      "zinc": 0.04,
      "manganese": 0,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_38.webp"
    },
    {
      "id": "39",
      "cmnName": "Raspberry",
      "scfName": "Rubus probus",
      "color1": Colors.red[100],
      "slDescription":
          "Raspberries are an important commercial fruit crop, widely grown in all temperate regions of the world.",
      "description":
          """The raspberry is the edible fruit of a multitude of plant species in the genus Rubus of the rose family. World production of raspberries in 2019 was 822,493 tonnes, led by Russia with approximately 21% of the total.\n\nWhat distinguishes the raspberry from its blackberry relatives is whether or not the torus (receptacle or stem) \"picks with\" (i.e., stays with) the fruit. When picking a blackberry fruit, the torus stays with the fruit. With a raspberry, the torus remains on the plant, leaving a hollow core in the raspberry fruit. The fruit is red, edible, and sweet but tart-flavoured, produced in summer or early autumn; in botanical terminology, it is not a berry at all, but an aggregate fruit of numerous drupelets around a central core. \n\nThe fruit is harvested when it comes off the receptacle easily and has turned a deep color (red, black, purple, or golden yellow, depending on the species and cultivar). This is when the fruits are ripest and sweetest.Raspberries are grown for the fresh fruit market and for commercial processing into individually quick frozen (IQF) fruit, pur\u00e9e, juice, or as dried fruit used in a variety of grocery products such as raspberry pie. \n""",
      "imgUrl": "f_39.webp",
      "calories": 53,
      "carb": 11.94,
      "sugar": 4.42,
      "fiber": 6.5,
      "fat": 0.65,
      "protein": 1.2,
      "water": 85.8,
      "vitA": 0,
      "vitB1": 0.032,
      "vitB2": 0.038,
      "vitB3": 0.598,
      "vitB5": 0.329,
      "vitB6": 0.055,
      "vitB7": 0,
      "vitB9": 0.021,
      "vitB12": 0,
      "vitC": 26.2,
      "vitD": 0,
      "vitE": 0.87,
      "vitK": 0.0078,
      "choline": 12.3,
      "potassium": 29,
      "chlorine": 0,
      "sodium": 0,
      "calcium": 25,
      "phosphorus": 29,
      "magnesium": 22,
      "iron": 0.69,
      "zinc": 0.42,
      "manganese": 0.67,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_39.webp"
    },
    {
      "id": "40",
      "cmnName": "Ugli",
      "scfName": "Citrus reticulata \u00d7 citrus paradisi",
      "color1": Colors.lime[100],
      "slDescription":
          "Ugli fruit is a large juicy yellow-skinned citrus fruit of the Caribbean: a cross between a tangerine, grapefruit, and orange",
      "description":
          """The Jamaican tangelo, also known by proprietary names ugli /\u02c8\u028c\u0261li/ fruit, uglifruit, and uniq fruit, is a citrus fruit that arose on the island of Jamaica through the natural hybridization of a tangerine or orange with a grapefruit (or pomelo), and is thus a tangelo. As a hybrid species, it is usually represented as Citrus reticulata \u00d7 paradisi.\n\nThe taste is often described as sourer than an orange and less bitter than a grapefruit, however, and is more commonly guessed to be a lemon\u2013tangerine hybrid. The fruit is seasonal from December to April. It is distributed in Europe and the United States between November and April, and is on occasion available from July to September.\n\n'UGLI' is a registered trademark of Cabel Hall Citrus Limited, under which it markets the fruit, the name being a variation of the word \"ugly\", which refers to the fruit's unsightly appearance, with rough, wrinkled, greenish-yellow rind, wrapped loosely around the orange pulpy citrus inside.\n""",
      "imgUrl": "f_40.webp",
      "calories": 47,
      "carb": 12,
      "sugar": 0,
      "fiber": 2,
      "fat": 0,
      "protein": 1,
      "water": 85.4,
      "vitA": 0,
      "vitB1": 0,
      "vitB2": 0,
      "vitB3": 0,
      "vitB5": 0,
      "vitB6": 0,
      "vitB7": 0,
      "vitB9": 0,
      "vitB12": 0,
      "vitC": 0,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0,
      "choline": 0,
      "potassium": 0,
      "chlorine": 0,
      "sodium": 0,
      "calcium": 0,
      "phosphorus": 0,
      "magnesium": 0,
      "iron": 0,
      "zinc": 0,
      "manganese": 0,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_40.webp"
    },
    {
      "id": "41",
      "cmnName": "Zapote/Sapote",
      "scfName": "Pouteria sapota",
      "color1": Colors.amber[100],
      "slDescription":
          "Sapote/Zapote is a edible fruit that has a rusty brown peel, is rather spherical, and measures about 5\u201310 cm (2\u20134 inches) in diameter. The reddish orange flesh is mild and musky-sweet in flavour with a creamy consistency. Each fruit contains a large, shiny brown seed.",
      "description":
          """Pouteria sapota,also called the mamey sapote, is a species of tree native to Mexico and Central America. The tree is also cultivated in the Caribbean. Its fruit is eaten in many Latin American countries. \n\nMamey sapote is a large and highly ornamental evergreen tree that can reach a height of 15 to 45 meters (49 to 148 ft) at maturity.The fruit is eaten raw or made into milkshakes, smoothies, ice cream and fruit bars. It can be used to produce marmalade and jelly.Some beauty products use oil pressed from the seed, otherwise known as sapayul oil.\n\nThe fruit is an excellent source of vitamin B6 and vitamin C, and is a good source of riboflavin, niacin, vitamin E, manganese, potassium and dietary fiber. Research has identified several new carotenoids from the ripe fruit.\n""",
      "imgUrl": "f_41.webp",
      "calories": 124,
      "carb": 32.1,
      "sugar": 20.14,
      "fiber": 5.4,
      "fat": 0.46,
      "protein": 1.45,
      "water": 65.8,
      "vitA": 0,
      "vitB1": 0.013,
      "vitB2": 0.116,
      "vitB3": 1.432,
      "vitB5": 0.397,
      "vitB6": 0.72,
      "vitB7": 0,
      "vitB9": 0.007,
      "vitB12": 0,
      "vitC": 23,
      "vitD": 0,
      "vitE": 2.11,
      "vitK": 0,
      "choline": 0,
      "potassium": 454,
      "chlorine": 0,
      "sodium": 7,
      "calcium": 18,
      "phosphorus": 26,
      "magnesium": 11,
      "iron": 0.78,
      "zinc": 0.19,
      "manganese": 0.204,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_41.webp"
    },
    {
      "id": "42",
      "cmnName": "Youngberry",
      "scfName": "Rubus caesius 'Youngberry'",
      "color1": Colors.purple[100],
      "slDescription":
          "Youngberries are a bramble fruit that resemble common blackberries but on a smaller scale. They have a solid core surrounded by fleshy drupes that are extremely fragile and larger than those of other blackberries. They are spherical to oblong with a tapering conical shape and turn a deep purplish-black when ripe. Youngberries are sweeter and more succulent than other blackberry varieties with a delicate texture bursting with juiciness.",
      "description":
          """The youngberry is a complex hybrid between three different berry species from the genus Rubus: raspberry, blackberry, and dewberry of the Rose family.The berries of the plant are eaten fresh or used to make juice, jam, and in recipes.\n\nThe youngberry was created in the early 20th century by B.M. Young in Louisiana by crossing the \"Phenomenal\" blackberry\u2013raspberry hybrid with the \"Mayes\" dewberry.It is similar to the Loganberry, \"nectarberry\", and Boysenberry in shape, color, and flavor. Youngberries can be grown in fertile clay soils.They are cultivated on small farms and home gardens in Oregon, Australia, and New Zealand.\n\nYoungberries are consumed fresh, or used for juice or in jams, pies, crumbles, fruit syrups, and country wines.\n""",
      "imgUrl": "f_42.webp",
      "calories": 43,
      "carb": 9.61,
      "sugar": 4.88,
      "fiber": 5.3,
      "fat": 0.49,
      "protein": 1.3,
      "water": 88.5,
      "vitA": 0,
      "vitB1": 0,
      "vitB2": 0,
      "vitB3": 0,
      "vitB5": 0,
      "vitB6": 0,
      "vitB7": 0,
      "vitB9": 0,
      "vitB12": 0,
      "vitC": 0,
      "vitD": 0,
      "vitE": 0,
      "vitK": 0,
      "choline": 0,
      "potassium": 162,
      "chlorine": 0,
      "sodium": 1,
      "calcium": 0,
      "phosphorus": 0,
      "magnesium": 0,
      "iron": 0,
      "zinc": 0,
      "manganese": 0,
      "copper": 0,
      "selenium": 0,
      "treeURL": "t_42.webp"
    }
  ];

  String _searchString = "";

  void sortFruits(bool alphabetically) {
    //if alphabetically is true then sort from A-Z or Z-A
    if (alphabetically) {
      _fruitsNew.sort((a, b) => a['cmnName'].compareTo(b['cmnName']));
    } else {
      _fruitsNew.sort((a, b) => b['cmnName'].compareTo(a['cmnName']));
    }
  }

  void searchFruitsProvider(String keyword) {
    _searchString = keyword;
    notifyListeners();
  }

  void loadAllFruits() {
    _searchString = "";
    notifyListeners();
  }

  List<Map<String, dynamic>> get fruitsListNew => 
      [..._fruitsNew];
      
  String get getSearchString => _searchString;
}
